#!/bin/bash -ex

if [[ -z "$1" || -z "$2" ]]; then
   echo "usage: $0 <image name> <efi app name>"
   exit 1
fi

parted $1 mklabel gpt
parted -- $1 mkpart boot fat32 1mib -1mib
LODEV=$(losetup -o 1048576 -f $1 --show)
mkfs.fat -F 32 $LODEV
mount $LODEV build/mnt
mkdir -p build/mnt/efi/boot
cp $2 build/mnt/efi/boot/bootx64.efi
umount build/mnt
losetup -d $LODEV
